"""add columns to sell_options

Revision ID: 89f1586442a9
Revises: a21aca0da51d
Create Date: 2022-01-12 19:05:42.004697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89f1586442a9"
down_revision = "a21aca0da51d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sell_option", sa.Column("strike", sa.Float(), nullable=True))
    op.add_column("sell_option", sa.Column("price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sell_option", "price")
    op.drop_column("sell_option", "strike")
    # ### end Alembic commands ###
